VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsDDLTMDetartic"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get table() As String

    table = "tmdetartic"

End Property

Public Property Get clave() As String

    clave = "clave"

End Property

Public Property Get clave_t() As String

    clave_t = "tmdetartic.clave"

End Property

Public Property Get hwnd() As String

    hwnd = "dat_hwnd"

End Property

Public Property Get hwnd_t() As String

    hwnd_t = "tmdetartic.dat_hwnd"

End Property

Public Property Get item() As String

    item = "item"

End Property

Public Property Get item_t() As String

    item_t = "tmdetartic.item"

End Property

Public Property Get cgoarticulo() As String

    cgoarticulo = "cgoarticulo"

End Property

Public Property Get cgoarticulo_t() As String

    cgoarticulo_t = "tmdetartic.cgoarticulo"

End Property

Public Property Get descripcion() As String

    descripcion = "descripcion"

End Property

Public Property Get descripcion_t() As String

    descripcion_t = "tmdetartic.descripcion"

End Property

Public Property Get cantidad() As String

    cantidad = "cantidad"

End Property

Public Property Get cantidad_t() As String

    cantidad_t = "tmdetartic.cantidad"

End Property

Public Property Get totalconiva() As String

    totalconiva = "totalconiva"

End Property

Public Property Get totalconiva_t() As String

    totalconiva_t = "tmdetartic.totalconiva"

End Property

Public Property Get totalsiniva() As String

    totalsiniva = "totalsiniva"

End Property

Public Property Get totalsiniva_t() As String

    totalsiniva_t = "tmdetartic.totalsiniva"

End Property

Public Property Get precioventaconiva() As String

    precioventaconiva = "precioventaconiva"

End Property

Public Property Get precioventaconiva_t() As String

    precioventaconiva_t = "tmdetartic.precioventaconiva"

End Property

Public Property Get precioventasiniva() As String

    precioventasiniva = "precioventasiniva"

End Property

Public Property Get precioventasiniva_t() As String

    precioventasiniva_t = "tmdetartic.precioventasiniva"

End Property

Public Property Get preciodescuentoconiva() As String

    preciodescuentoconiva = "preciodescuentoconiva"

End Property

Public Property Get preciodescuentoconiva_t() As String

    preciodescuentoconiva_t = "tmdetartic.preciodescuentoconiva"

End Property

Public Property Get preciodescuentosiniva() As String

    preciodescuentosiniva = "preciodescuentosiniva"

End Property

Public Property Get preciodescuentosiniva_t() As String

    preciodescuentosiniva_t = "tmdetartic.preciodescuentosiniva"

End Property

Public Property Get preciocomprasiniva() As String

    preciocomprasiniva = "preciocomprasiniva"

End Property

Public Property Get preciocomprasiniva_t() As String

    preciocomprasiniva_t = "tmdetartic.preciocomprasiniva"

End Property

Public Property Get item2() As String

    item2 = "item2"

End Property

Public Property Get item2_t() As String

    item2_t = "tmdetartic.item2"

End Property

Public Property Get iva105() As String

    iva105 = "iva105"

End Property

Public Property Get iva105_t() As String

    iva105_t = "tmdetartic.iva105"

End Property

Public Property Get exento() As String

    exento = "exento"

End Property

Public Property Get exento_t() As String

    exento_t = "tmdetartic.exento"

End Property

Public Property Get nrofactura() As String

    nrofactura = "nrofactura"

End Property

Public Property Get nrofactura_t() As String

    nrofactura_t = "tmdetartic.nrofactura"

End Property

Public Property Get fechafactura() As String

    fechafactura = "fechafactura"

End Property

Public Property Get fechafactura_t() As String

    fechafactura_t = "tmdetartic.fechafactura"

End Property

Public Property Get descuento() As String

    descuento = "descuento"

End Property

Public Property Get descuento_t() As String

    descuento_t = "tmdetartic.descuento"

End Property

