VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsDDLMovclie"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get table() As String

    table = "movclie"

End Property

Public Property Get clave() As String

    clave = "clave"

End Property

Public Property Get clave_t() As String

    clave_t = "movclie.clave"

End Property

Public Property Get negID() As String

    negID = "mcl_neg_id"

End Property

Public Property Get negID_t() As String

    negID_t = "movclie.mcl_neg_id"

End Property

Public Property Get empID() As String

    empID = "mcl_emp_id"

End Property

Public Property Get empID_t() As String

    empID_t = "movclie.mcl_emp_id"

End Property

Public Property Get cgoclie() As String

    cgoclie = "cgoclie"

End Property

Public Property Get cgoclie_t() As String

    cgoclie_t = "movclie.cgoclie"

End Property

Public Property Get cgocomprob() As String

    cgocomprob = "cgocomprob"

End Property

Public Property Get cgocomprob_t() As String

    cgocomprob_t = "movclie.cgocomprob"

End Property

Public Property Get fechacomprob() As String

    fechacomprob = "fechacomprob"

End Property

Public Property Get fechacomprob_t() As String

    fechacomprob_t = "movclie.fechacomprob"

End Property

Public Property Get fechavenc() As String

    fechavenc = "mcl_fechavenc"

End Property

Public Property Get fechavenc_t() As String

    fechavenc_t = "movclie.mcl_fechavenc"

End Property

Public Property Get prefijo() As String

    prefijo = "prefijo"

End Property

Public Property Get prefijo_t() As String

    prefijo_t = "movclie.prefijo"

End Property

Public Property Get nroComprob() As String

    nroComprob = "nrocomprob"

End Property

Public Property Get nroComprob_t() As String

    nroComprob_t = "movclie.nrocomprob"

End Property

Public Property Get importe() As String

    importe = "importe"

End Property

Public Property Get importe_t() As String

    importe_t = "movclie.importe"

End Property

Public Property Get cancelado() As String

    cancelado = "cancelado"

End Property

Public Property Get cancelado_t() As String

    cancelado_t = "movclie.cancelado"

End Property

Public Property Get netosindescuento() As String

    netosindescuento = "netosindescuento"

End Property

Public Property Get netosindescuento_t() As String

    netosindescuento_t = "movclie.netosindescuento"

End Property

Public Property Get neto() As String

    neto = "neto"

End Property

Public Property Get neto_t() As String

    neto_t = "movclie.neto"

End Property

Public Property Get netocancelado() As String

    netocancelado = "netocancelado"

End Property

Public Property Get netocancelado_t() As String

    netocancelado_t = "movclie.netocancelado"

End Property

Public Property Get montoiva() As String

    montoiva = "montoiva"

End Property

Public Property Get montoiva_t() As String

    montoiva_t = "movclie.montoiva"

End Property

Public Property Get montoexento() As String

    montoexento = "montoexento"

End Property

Public Property Get montoexento_t() As String

    montoexento_t = "movclie.montoexento"

End Property

Public Property Get recibo() As String

    recibo = "recibo"

End Property

Public Property Get recibo_t() As String

    recibo_t = "movclie.recibo"

End Property

Public Property Get anulada() As String

    anulada = "anulada"

End Property

Public Property Get anulada_t() As String

    anulada_t = "movclie.anulada"

End Property

Public Property Get tipocompro() As String

    tipocompro = "tipocompro"

End Property

Public Property Get tipocompro_t() As String

    tipocompro_t = "movclie.tipocompro"

End Property

Public Property Get letras() As String

    letras = "mcl_letras"

End Property

Public Property Get letras_t() As String

    letras_t = "movclie.mcl_letras"

End Property

Public Property Get iva() As String

    iva = "mcl_iva"

End Property

Public Property Get iva_t() As String

    iva_t = "movclie.mcl_iva"

End Property

Public Property Get observaciones() As String

    observaciones = "mcl_observaciones"

End Property

Public Property Get observaciones_t() As String

    observaciones_t = "movclie.mcl_observaciones"

End Property

Public Property Get cae() As String

    cae = "mcl_cae"

End Property

Public Property Get cae_t() As String

    cae_t = "movclie.mcl_cae"

End Property

Public Property Get caevenc() As String

    caevenc = "mcl_caevenc"

End Property

Public Property Get caevenc_t() As String

    caevenc_t = "movclie.mcl_caevenc"

End Property

Public Property Get barras() As String

    barras = "mcl_barras"

End Property

Public Property Get barras_t() As String

    barras_t = "movclie.mcl_barras"

End Property




