VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsDDLDetartic"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get table() As String

    table = "detartic"

End Property

Public Property Get clave() As String

    clave = "clave"

End Property

Public Property Get clave_t() As String

    clave_t = "detartic.clave"

End Property

Public Property Get clavemovclie() As String

    clavemovclie = "clavemovclie"

End Property

Public Property Get clavemovclie_t() As String

    clavemovclie_t = "detartic.clavemovclie"

End Property

Public Property Get cgocomprob() As String

    cgocomprob = "cgocomprob"

End Property

Public Property Get cgocomprob_t() As String

    cgocomprob_t = "detartic.cgocomprob"

End Property

Public Property Get item() As String

    item = "item"

End Property

Public Property Get item_t() As String

    item_t = "detartic.item"

End Property

Public Property Get negid() As String

    negid = "dea_neg_id"

End Property

Public Property Get negid_t() As String

    negid_t = "detartic.dea_neg_id"

End Property

Public Property Get cgoartic() As String

    cgoartic = "cgoartic"

End Property

Public Property Get cgoartic_t() As String

    cgoartic_t = "detartic.cgoartic"

End Property

Public Property Get descripcion() As String

    descripcion = "dea_descripcion"

End Property

Public Property Get descripcion_t() As String

    descripcion_t = "detartic.dea_descripcion"

End Property

Public Property Get cantidad() As String

    cantidad = "cantidad"

End Property

Public Property Get cantidad_t() As String

    cantidad_t = "detartic.cantidad"

End Property

Public Property Get precioventasiniva() As String

    precioventasiniva = "precioventasiniva"

End Property

Public Property Get precioventasiniva_t() As String

    precioventasiniva_t = "detartic.precioventasiniva"

End Property

Public Property Get precioventaconiva() As String

    precioventaconiva = "precioventaconiva"

End Property

Public Property Get precioventaconiva_t() As String

    precioventaconiva_t = "detartic.precioventaconiva"

End Property

Public Property Get preciodescuentosiniva() As String

    preciodescuentosiniva = "preciodescuentosiniva"

End Property

Public Property Get preciodescuentosiniva_t() As String

    preciodescuentosiniva_t = "detartic.preciodescuentosiniva"

End Property

Public Property Get preciodescuentoconiva() As String

    preciodescuentoconiva = "preciodescuentoconiva"

End Property

Public Property Get preciodescuentoconiva_t() As String

    preciodescuentoconiva_t = "detartic.preciodescuentoconiva"

End Property

Public Property Get iva105() As String

    iva105 = "iva105"

End Property

Public Property Get iva105_t() As String

    iva105_t = "detartic.iva105"

End Property

Public Property Get exento() As String

    exento = "exento"

End Property

Public Property Get exento_t() As String

    exento_t = "detartic.exento"

End Property

Public Property Get fecha() As String

    fecha = "fecha"

End Property

Public Property Get fecha_t() As String

    fecha_t = "detartic.fecha"

End Property

Public Property Get fechafac() As String

    fechafac = "fechafac"

End Property

Public Property Get fechafac_t() As String

    fechafac_t = "detartic.fechafac"

End Property

Public Property Get preciocomprasiniva() As String

    preciocomprasiniva = "preciocomprasiniva"

End Property

Public Property Get preciocomprasiniva_t() As String

    preciocomprasiniva_t = "detartic.preciocomprasiniva"

End Property

Public Property Get descuento() As String

    descuento = "dea_descuento"

End Property

Public Property Get descuento_t() As String

    descuento_t = "detartic.dea_descuento"

End Property

